Проектная работа «Посмотри в окно»
devPavelM/posmotri_v_okno pull request #1
Opened 2024-11-09 14:12 UTC by devPavelM

2024-11-09 16:02 UTC, seginel requested changes
Здравствуйте, у вас получилась достойная работа, но в ней есть замечания - здесь понадобятся доработки.
 Вы справитесь, желаю вам успехов.

### Что понравилось

* Аккуратное форматирование кода
* Абсолютное позиционирование не используется без необходимости;
* Для стилизации интерактивных элементов используется  `outline`;
* Для построения элементов использованы flex/grid.
* Заданы все состояния для интерактивных элементов из макета
* Сброшены состояния `:focus` у интерактивных элементов

### Что нужно поправить

* Все комментарии "Надо исправить" в коде.
* Стоит напомнить, что все замечания не придумываются ревьюером на ходу. Они формируются на основе чеклиста и брифа к заданию. Если соблюсти все требования чеклиста и рекомендаций в брифе, то работа будет сразу же принята. Поэтому перед отправкой на следующую итерацию рекомендую самостоятельно пройтись по брифу и чеклисту и при необходимости поправить все проблемные места. Это позволит быстрее принять работу.

### Что можно лучше

* Все комментарии "Можно лучше" в коде.
* При написании CSS-правил старайтесь, чтобы они были расположены в примерном соответствии с позицией элементов в DOM

Комментарии "можно лучше" носят рекомендательный характер, их выполнение остается на Ваше усмотрение. Комментарии "надо исправить" являются обязательными, при выполнении всех "надо исправить" работа будет зачтена. Удачи

2024-11-09 16:02 UTC, seginel commented on styles/style.css
> +  display: flex;
Отлично - для разметки формы использованы флексы.

2024-11-09 16:02 UTC, seginel commented on styles/style.css
> +  overflow-y: auto;
Отлично - полоса прокрутки отображается только когда контейнер переполнен элементами.

2024-11-09 16:02 UTC, seginel commented on styles/style.css
> +  object-fit: cover;
Отлично - видео будет занимать всю доступную область и не будет искажаться.

2024-11-09 16:02 UTC, seginel commented on styles/style.css
> +  inline-size: 711px;
Отлично - в работе использованы логические свойства

2024-11-09 16:02 UTC, seginel commented on styles/style.css
> +  appearance: none;
Отлично - использован трюк со свойством appearance, чтобы привести поле ввода к общему виду во всех браузерах.

2024-11-09 16:02 UTC, seginel commented on styles/style.css
> +  color: rgb(255 255 255 / 0.7);
Можно лучше
В макете серый цвет показан для подсказки (плейсхолдера), а для введённого текста в инпуте текст обычно должен отличаться. К сожалению, в макете вариант с заполненным инпутом не показан, но, чтобы отличать подсказку от текста, я бы порекомендовал для инпута использовать белый цвет `#fff`.

2024-11-09 16:02 UTC, seginel commented on styles/style.css
> +  block-size: 34px;
Можно лучше: 
У кнопки не стоит жёстко ограничивать высоту, вместо этого лучше использовать более мягкое свойство -`min-block-size`, либо через внутренние отступы `padding` сверху и снизу.

В отличие от других мест, где высоту нужно вообще удалить, здесь в кнопке всегда будет какой-то текст. Кнопка без текста не будет иметь смысл, поэтому у кнопки всегда будет какая-то минимальная высота, которую удобно задать через свойство `min-`. Здесь это лишь рекомендация: в большинстве случаев у кнопки текст очень короткий - на одну строку, поэтому и свойство `block-size` здесь вполне допустимо.

2024-11-09 16:02 UTC, seginel commented on styles/style.css
> +  outline: none;
Отлично - у всех интерактивных элементов сброшено состояние `:focus`.

2024-11-09 16:02 UTC, seginel commented on styles/style.css
> +.search-form__pseudo-checkbox {
Надо исправить
Согласно чеклисту, в работе не должно быть дублирующихся селекторов. Стили для одного и того же селектора нужно прописать в одном месте.

2024-11-09 16:02 UTC, seginel commented on styles/style.css
> +.content__card-link_current {
Отлично - указан стиль для текущей выбранной карточки

2024-11-09 16:02 UTC, seginel commented on styles/style.css
> +.content__list-item:active {
Надо исправить:
Это лишний селектор. Состояние active стоит реализовать у интерактивного элемента и вы уже верно реализовали это ниже у ссылки `.content__card-link`

2024-11-10 09:43 UTC, devPavelM commented
@seginel Добрый день Антон!
Спасибо за отличное ревью и полезные комментарии!
Исправил ошибки.

2024-11-10 16:40 UTC, seginel approved these changes
Спасибо за правки. Вы внесли исправления по всем замечаниям и хочу поздравить - Вы отлично справились с выполнением проектной работы. По странице у меня больше нет замечаний: страница соответствует макету и требованиям чеклиста.
Работу принимаю. Удачи в дальнейшем обучении.

2024-11-10 19:20 UTC, merged